global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'monteweb-backend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['backend:8080']
        labels:
          application: monteweb
